apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deployment
  labels:
    app: speedtestcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      hostNetwork: true
      containers:
      - name: speedtest
        image: lalx/speedtest-cli
        env:
        - name: HOST_HOSTNAME
          value: hostname
